// ============================================================
// 1. PRODUCT DATA — 12 realistic products across 5 categories
// ============================================================

export const DEMO_PRODUCTS = [
    {
        id: 'PRD-001',
        product_name: 'Galaxy Pro Max X1',
        category: 'Electronics',
        sku: 'ELEC-GPX1-256',
        manufacturer: 'TechNova Solutions',
        description: 'Flagship smartphone with 6.8" AMOLED display, 256GB storage',
    },
    {
        id: 'PRD-002',
        product_name: 'NovaPods Ultra',
        category: 'Electronics',
        sku: 'ELEC-NPU-BLK',
        manufacturer: 'TechNova Solutions',
        description: 'Wireless ANC earbuds with 40hr battery, spatial audio',
    },
    {
        id: 'PRD-003',
        product_name: 'SmartWatch Series 9',
        category: 'Electronics',
        sku: 'ELEC-SWS9-TI',
        manufacturer: 'TechNova Solutions',
        description: 'Titanium smartwatch with health monitoring suite',
    },
    {
        id: 'PRD-004',
        product_name: 'Amoxicillin 500mg',
        category: 'Pharmaceuticals',
        sku: 'PHAR-AMX-500',
        manufacturer: 'MedCore Pharmaceuticals',
        description: 'Broad-spectrum antibiotic, 30 capsule blister pack',
    },
    {
        id: 'PRD-005',
        product_name: 'InsulinPen FlexiDose',
        category: 'Pharmaceuticals',
        sku: 'PHAR-IPF-300',
        manufacturer: 'MedCore Pharmaceuticals',
        description: 'Pre-filled insulin pen, 300 IU, refrigerated transport required',
    },
    {
        id: 'PRD-006',
        product_name: 'Organic Darjeeling Tea',
        category: 'Food',
        sku: 'FOOD-ODT-500',
        manufacturer: 'Himalaya Organics',
        description: 'Premium first flush Darjeeling tea leaves, 500g pack',
    },
    {
        id: 'PRD-007',
        product_name: 'Cold-Pressed Olive Oil',
        category: 'Food',
        sku: 'FOOD-CPOO-1L',
        manufacturer: 'MediterraFoods',
        description: 'Extra virgin cold-pressed olive oil, 1L glass bottle',
    },
    {
        id: 'PRD-008',
        product_name: 'Swiss Chronograph Royal',
        category: 'Luxury Goods',
        sku: 'LUX-SCR-GLD',
        manufacturer: 'Aurelian Timepieces',
        description: 'Hand-assembled 18K gold chronograph, sapphire crystal',
    },
    {
        id: 'PRD-009',
        product_name: 'Heritage Leather Satchel',
        category: 'Luxury Goods',
        sku: 'LUX-HLS-BRN',
        manufacturer: 'Maison Duval',
        description: 'Full-grain Italian leather satchel, limited edition',
    },
    {
        id: 'PRD-010',
        product_name: 'Turbo Brake Disc Set',
        category: 'Automotive Parts',
        sku: 'AUTO-TBD-FR4',
        manufacturer: 'Precision AutoParts',
        description: 'Performance ventilated brake discs, front axle set of 4',
    },
    {
        id: 'PRD-011',
        product_name: 'HyperSpark Ignition Coil',
        category: 'Automotive Parts',
        sku: 'AUTO-HSI-V8',
        manufacturer: 'Precision AutoParts',
        description: 'High-performance ignition coil pack for V8 engines',
    },
    {
        id: 'PRD-012',
        product_name: 'Vitamin D3 Gummies',
        category: 'Pharmaceuticals',
        sku: 'PHAR-VD3-60',
        manufacturer: 'WellLife Nutraceuticals',
        description: 'Chewable vitamin D3 supplement, 60 count, berry flavor',
    },
];

// ============================================================
// 2. PRODUCT BATCHES — multiple batches per product
// ============================================================

export const DEMO_BATCHES = [
    {
        batch_id: 'BAT-ELEC-001',
        product_id: 'PRD-001',
        production_date: '2025-10-15',
        expiry_date: null,
        origin_location: 'Shenzhen, China',
        current_stage: 'Retailer',
        qr_code_id: 'QR-BAT-ELEC-001',
        status: 'Delivered',
    },
    {
        batch_id: 'BAT-ELEC-002',
        product_id: 'PRD-001',
        production_date: '2025-12-01',
        expiry_date: null,
        origin_location: 'Shenzhen, China',
        current_stage: 'Distributor',
        qr_code_id: 'QR-BAT-ELEC-002',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-ELEC-003',
        product_id: 'PRD-002',
        production_date: '2025-11-20',
        expiry_date: null,
        origin_location: 'Dongguan, China',
        current_stage: 'Warehouse',
        qr_code_id: 'QR-BAT-ELEC-003',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-ELEC-004',
        product_id: 'PRD-003',
        production_date: '2026-01-05',
        expiry_date: null,
        origin_location: 'Taipei, Taiwan',
        current_stage: 'Logistics',
        qr_code_id: 'QR-BAT-ELEC-004',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-PHAR-001',
        product_id: 'PRD-004',
        production_date: '2025-09-01',
        expiry_date: '2027-09-01',
        origin_location: 'Hyderabad, India',
        current_stage: 'Retailer',
        qr_code_id: 'QR-BAT-PHAR-001',
        status: 'Delivered',
    },
    {
        batch_id: 'BAT-PHAR-002',
        product_id: 'PRD-004',
        production_date: '2026-01-10',
        expiry_date: '2028-01-10',
        origin_location: 'Hyderabad, India',
        current_stage: 'Warehouse',
        qr_code_id: 'QR-BAT-PHAR-002',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-PHAR-003',
        product_id: 'PRD-005',
        production_date: '2026-02-01',
        expiry_date: '2026-08-01',
        origin_location: 'Basel, Switzerland',
        current_stage: 'Logistics',
        qr_code_id: 'QR-BAT-PHAR-003',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-FOOD-001',
        product_id: 'PRD-006',
        production_date: '2025-08-15',
        expiry_date: '2026-08-15',
        origin_location: 'Darjeeling, India',
        current_stage: 'Customer',
        qr_code_id: 'QR-BAT-FOOD-001',
        status: 'Delivered',
    },
    {
        batch_id: 'BAT-FOOD-002',
        product_id: 'PRD-006',
        production_date: '2026-01-20',
        expiry_date: '2027-01-20',
        origin_location: 'Darjeeling, India',
        current_stage: 'Distributor',
        qr_code_id: 'QR-BAT-FOOD-002',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-FOOD-003',
        product_id: 'PRD-007',
        production_date: '2025-11-01',
        expiry_date: '2027-05-01',
        origin_location: 'Crete, Greece',
        current_stage: 'Retailer',
        qr_code_id: 'QR-BAT-FOOD-003',
        status: 'Delivered',
    },
    {
        batch_id: 'BAT-LUX-001',
        product_id: 'PRD-008',
        production_date: '2025-06-01',
        expiry_date: null,
        origin_location: 'Geneva, Switzerland',
        current_stage: 'Retailer',
        qr_code_id: 'QR-BAT-LUX-001',
        status: 'Delivered',
    },
    {
        batch_id: 'BAT-LUX-002',
        product_id: 'PRD-009',
        production_date: '2025-12-10',
        expiry_date: null,
        origin_location: 'Florence, Italy',
        current_stage: 'Logistics',
        qr_code_id: 'QR-BAT-LUX-002',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-AUTO-001',
        product_id: 'PRD-010',
        production_date: '2025-10-20',
        expiry_date: null,
        origin_location: 'Stuttgart, Germany',
        current_stage: 'Distributor',
        qr_code_id: 'QR-BAT-AUTO-001',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-AUTO-002',
        product_id: 'PRD-011',
        production_date: '2026-02-15',
        expiry_date: null,
        origin_location: 'Detroit, USA',
        current_stage: 'Manufacturer',
        qr_code_id: 'QR-BAT-AUTO-002',
        status: 'Processing',
    },
    {
        batch_id: 'BAT-PHAR-004',
        product_id: 'PRD-012',
        production_date: '2026-01-25',
        expiry_date: '2027-07-25',
        origin_location: 'Mumbai, India',
        current_stage: 'Warehouse',
        qr_code_id: 'QR-BAT-PHAR-004',
        status: 'In Transit',
    },
    {
        batch_id: 'BAT-FOOD-004-SUS',
        product_id: 'PRD-006',
        production_date: '2025-08-15',
        expiry_date: '2026-08-15',
        origin_location: 'Unknown',
        current_stage: 'Flagged',
        qr_code_id: 'QR-BAT-FOOD-004-FAKE',
        status: 'Flagged',
    },
];
