// ============================================================
// 5. LIVE SHIPMENT DATA — 10 active shipments
// ============================================================

export const DEMO_SHIPMENTS = [
    {
        shipment_id: 'SHP-001',
        batch_id: 'BAT-ELEC-002',
        product_name: 'Galaxy Pro Max X1',
        current_location: 'Mumbai, India',
        next_destination: 'New Delhi, India',
        status: 'In Transit',
        last_updated: '2026-03-09T06:15:00Z',
    },
    {
        shipment_id: 'SHP-002',
        batch_id: 'BAT-ELEC-003',
        product_name: 'NovaPods Ultra',
        current_location: 'Dongguan, China',
        next_destination: 'Mumbai, India',
        status: 'In Transit',
        last_updated: '2026-03-09T04:30:00Z',
    },
    {
        shipment_id: 'SHP-003',
        batch_id: 'BAT-ELEC-004',
        product_name: 'SmartWatch Series 9',
        current_location: 'Singapore Port',
        next_destination: 'Dubai, UAE',
        status: 'In Transit',
        last_updated: '2026-03-08T22:45:00Z',
    },
    {
        shipment_id: 'SHP-004',
        batch_id: 'BAT-PHAR-002',
        product_name: 'Amoxicillin 500mg',
        current_location: 'Hyderabad, India',
        next_destination: 'Dubai, UAE',
        status: 'Pending Pickup',
        last_updated: '2026-03-09T07:00:00Z',
    },
    {
        shipment_id: 'SHP-005',
        batch_id: 'BAT-PHAR-003',
        product_name: 'InsulinPen FlexiDose',
        current_location: 'Dubai, UAE',
        next_destination: 'Mumbai, India',
        status: 'In Transit',
        last_updated: '2026-03-09T05:20:00Z',
    },
    {
        shipment_id: 'SHP-006',
        batch_id: 'BAT-FOOD-002',
        product_name: 'Organic Darjeeling Tea',
        current_location: 'Mumbai, India',
        next_destination: 'New Delhi, India',
        status: 'In Transit',
        last_updated: '2026-03-09T03:10:00Z',
    },
    {
        shipment_id: 'SHP-007',
        batch_id: 'BAT-LUX-002',
        product_name: 'Heritage Leather Satchel',
        current_location: 'Rotterdam, Netherlands',
        next_destination: 'Paris, France',
        status: 'In Transit',
        last_updated: '2026-03-08T18:50:00Z',
    },
    {
        shipment_id: 'SHP-008',
        batch_id: 'BAT-AUTO-001',
        product_name: 'Turbo Brake Disc Set',
        current_location: 'Rotterdam, Netherlands',
        next_destination: 'Frankfurt, Germany',
        status: 'In Transit',
        last_updated: '2026-03-09T01:30:00Z',
    },
    {
        shipment_id: 'SHP-009',
        batch_id: 'BAT-PHAR-004',
        product_name: 'Vitamin D3 Gummies',
        current_location: 'Mumbai, India',
        next_destination: 'Bangalore, India',
        status: 'Pending Pickup',
        last_updated: '2026-03-09T08:00:00Z',
    },
    {
        shipment_id: 'SHP-010',
        batch_id: 'BAT-AUTO-002',
        product_name: 'HyperSpark Ignition Coil',
        current_location: 'Detroit, USA',
        next_destination: 'Chicago, USA',
        status: 'Processing',
        last_updated: '2026-03-09T02:40:00Z',
    },
];

// ============================================================
// 6. QR VERIFICATION LOGS — valid and suspicious scans
// ============================================================

export const DEMO_QR_LOGS = [
    {
        scan_id: 'SCN-001',
        product_name: 'Galaxy Pro Max X1',
        batch_id: 'BAT-ELEC-001',
        scan_location: 'Mumbai, India',
        scanner_type: 'Retail POS',
        verification_result: 'Valid',
        timestamp: '2026-03-08T10:30:00Z',
    },
    {
        scan_id: 'SCN-002',
        product_name: 'Amoxicillin 500mg',
        batch_id: 'BAT-PHAR-001',
        scan_location: 'Bangalore, India',
        scanner_type: 'Pharmacy Scanner',
        verification_result: 'Valid',
        timestamp: '2026-03-08T11:15:00Z',
    },
    {
        scan_id: 'SCN-003',
        product_name: 'Swiss Chronograph Royal',
        batch_id: 'BAT-LUX-001',
        scan_location: 'Paris, France',
        scanner_type: 'Boutique Scanner',
        verification_result: 'Valid',
        timestamp: '2026-03-07T16:45:00Z',
    },
    {
        scan_id: 'SCN-004',
        product_name: 'Organic Darjeeling Tea',
        batch_id: 'BAT-FOOD-001',
        scan_location: 'Mumbai, India',
        scanner_type: 'Customer Mobile App',
        verification_result: 'Valid',
        timestamp: '2026-03-08T09:20:00Z',
    },
    {
        scan_id: 'SCN-005',
        product_name: 'Cold-Pressed Olive Oil',
        batch_id: 'BAT-FOOD-003',
        scan_location: 'Mumbai, India',
        scanner_type: 'Retail POS',
        verification_result: 'Valid',
        timestamp: '2026-03-07T14:00:00Z',
    },
    {
        scan_id: 'SCN-006',
        product_name: 'Organic Darjeeling Tea',
        batch_id: 'BAT-FOOD-004-SUS',
        scan_location: 'Unknown Location',
        scanner_type: 'Unknown Device',
        verification_result: 'Suspicious — Unregistered batch origin',
        timestamp: '2026-03-01T03:45:00Z',
    },
    {
        scan_id: 'SCN-007',
        product_name: 'Galaxy Pro Max X1',
        batch_id: 'BAT-ELEC-001',
        scan_location: 'Lucknow, India',
        scanner_type: 'Customer Mobile App',
        verification_result: 'Suspicious — Duplicate scan from unauthorized location',
        timestamp: '2026-03-05T22:10:00Z',
    },
    {
        scan_id: 'SCN-008',
        product_name: 'Turbo Brake Disc Set',
        batch_id: 'BAT-AUTO-001',
        scan_location: 'Rotterdam, Netherlands',
        scanner_type: 'Warehouse Scanner',
        verification_result: 'Valid',
        timestamp: '2026-03-06T08:30:00Z',
    },
    {
        scan_id: 'SCN-009',
        product_name: 'InsulinPen FlexiDose',
        batch_id: 'BAT-PHAR-003',
        scan_location: 'Dubai, UAE',
        scanner_type: 'Cold Chain Monitor',
        verification_result: 'Valid',
        timestamp: '2026-03-05T13:00:00Z',
    },
    {
        scan_id: 'SCN-010',
        product_name: 'Heritage Leather Satchel',
        batch_id: 'BAT-LUX-002',
        scan_location: 'Brussels, Belgium',
        scanner_type: 'Customer Mobile App',
        verification_result: 'Suspicious — Product not yet delivered to retailer',
        timestamp: '2026-03-08T20:15:00Z',
    },
    {
        scan_id: 'SCN-011',
        product_name: 'NovaPods Ultra',
        batch_id: 'BAT-ELEC-003',
        scan_location: 'Dongguan, China',
        scanner_type: 'Warehouse Scanner',
        verification_result: 'Valid',
        timestamp: '2026-03-07T07:45:00Z',
    },
    {
        scan_id: 'SCN-012',
        product_name: 'Vitamin D3 Gummies',
        batch_id: 'BAT-PHAR-004',
        scan_location: 'Mumbai, India',
        scanner_type: 'Warehouse Scanner',
        verification_result: 'Valid',
        timestamp: '2026-03-08T06:00:00Z',
    },
];
